/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameLog.java
 *
 * Created on Sep 14, 2011, 5:14:36 PM
 */
package rssi_graph;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author ph4r05
 */
public class JFrameLog extends javax.swing.JFrame {

    // refference to parent?
    protected RSSI_graphView parentPanel;
    
    /** Creates new form JFrameLog */
    public JFrameLog() {
        initComponents();
        
        // exit on close
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    }    

    public RSSI_graphView getParentPanel() {
        return parentPanel;
    }

    public void setParentPanel(RSSI_graphView parentPanel) {
        this.parentPanel = parentPanel;
    }

    public JPanelLogger getjPanelLogger1() {
        return jPanelLogger1;
    }

    public void setjPanelLogger1(JPanelLogger jPanelLogger1) {
        this.jPanelLogger1 = jPanelLogger1;
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogger1 = new rssi_graph.JPanelLogger();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanelLogger1.setName("jPanelLogger1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogger1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogger1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrameLog().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rssi_graph.JPanelLogger jPanelLogger1;
    // End of variables declaration//GEN-END:variables
}
