/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package rssi_graph;

/**
 * Data record of RSSIresponse
 * Used to store incoming data samples from mobile nodes
 *
 * @author ph4r05
 */
public class RSSIResponseRecord {
    private int nodeID_report_from;

    // counter is independent on nodeID_report_from since its generated by mobile node
    private int counter;

    // rssi of data sample from mobile node
    // sampled by {basestation,static node}
    private int rssi;

    // extensions
    private int mobile_txpower;

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RSSIResponseRecord other = (RSSIResponseRecord) obj;
        if (this.nodeID_report_from != other.nodeID_report_from) {
            return false;
        }
        if (this.counter != other.counter) {
            return false;
        }
        if (this.rssi != other.rssi) {
            return false;
        }
        if (this.mobile_txpower != other.mobile_txpower) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 53 * hash + this.nodeID_report_from;
        hash = 53 * hash + (int) (this.counter ^ (this.counter >>> 32));
        hash = 53 * hash + this.rssi;
        hash = 53 * hash + this.mobile_txpower;
        return hash;
    }

    public int getCounter() {
        return counter;
    }

    public void setCounter(int counter) {
        this.counter = counter;
    }

    public int getMobile_txpower() {
        return mobile_txpower;
    }

    public void setMobile_txpower(int mobile_txpower) {
        this.mobile_txpower = mobile_txpower;
    }

    public int getNodeID_report_from() {
        return nodeID_report_from;
    }

    public void setNodeID_report_from(int nodeID_report_from) {
        this.nodeID_report_from = nodeID_report_from;
    }

    public int getRssi() {
        return rssi;
    }

    public void setRssi(int rssi) {
        this.rssi = rssi;
    }
}
