/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jDialogLoadData.java
 *
 * Created on Apr 8, 2011, 4:18:00 PM
 */

package rssi_graph.rssi;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import rssi_localization.JPannelLoggerLogElement;
import rssi_localization.RSSI_graphApp;

/**
 *
 * @author ph4r05
 */
public class jDialogLoadData extends javax.swing.JDialog {

    /**
     * parent panel where show button was pressed
     */
    protected javax.swing.JPanel parentPanel = null;

    /** Creates new form jDialogLoadData */
    public jDialogLoadData(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboXValue = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextParamConstant = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextMinimalRefDistance = new javax.swing.JTextField();
        jTextMaximalRefDistance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextParamDirectMulti = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckFitCurve = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jCheckXGroupTest = new javax.swing.JCheckBox();
        jCheckXGroupMobileId = new javax.swing.JCheckBox();
        jCheckXGroupStaticId = new javax.swing.JCheckBox();
        jCheckXGroupTx = new javax.swing.JCheckBox();
        jCheckXGroupMid = new javax.swing.JCheckBox();
        jCheckConnectWithLine = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(rssi_localization.RSSI_graphApp.class).getContext().getResourceMap(jDialogLoadData.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jComboXValue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Distance [cm]", "mid", "NodeID", "TxPower", "NodeID+TxPower" }));
        jComboXValue.setName("jComboXValue"); // NOI18N
        jComboXValue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboXValueItemStateChanged(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jTextParamConstant.setText(resourceMap.getString("jTextParamConstant.text")); // NOI18N
        jTextParamConstant.setName("jTextParamConstant"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jTextMinimalRefDistance.setText(resourceMap.getString("jTextMinimalRefDistance.text")); // NOI18N
        jTextMinimalRefDistance.setName("jTextMinimalRefDistance"); // NOI18N

        jTextMaximalRefDistance.setText(resourceMap.getString("jTextMaximalRefDistance.text")); // NOI18N
        jTextMaximalRefDistance.setName("jTextMaximalRefDistance"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jTextParamDirectMulti.setText(resourceMap.getString("jTextParamDirectMulti.text")); // NOI18N
        jTextParamDirectMulti.setToolTipText(resourceMap.getString("jTextParamDirectMulti.toolTipText")); // NOI18N
        jTextParamDirectMulti.setName("jTextParamDirectMulti"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jCheckFitCurve.setSelected(true);
        jCheckFitCurve.setText(resourceMap.getString("jCheckFitCurve.text")); // NOI18N
        jCheckFitCurve.setName("jCheckFitCurve"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setToolTipText(resourceMap.getString("jPanel1.toolTipText")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jCheckXGroupTest.setSelected(true);
        jCheckXGroupTest.setText(resourceMap.getString("jCheckXGroupTest.text")); // NOI18N
        jCheckXGroupTest.setName("jCheckXGroupTest"); // NOI18N

        jCheckXGroupMobileId.setText(resourceMap.getString("jCheckXGroupMobileId.text")); // NOI18N
        jCheckXGroupMobileId.setName("jCheckXGroupMobileId"); // NOI18N

        jCheckXGroupStaticId.setSelected(true);
        jCheckXGroupStaticId.setText(resourceMap.getString("jCheckXGroupStaticId.text")); // NOI18N
        jCheckXGroupStaticId.setName("jCheckXGroupStaticId"); // NOI18N

        jCheckXGroupTx.setSelected(true);
        jCheckXGroupTx.setText(resourceMap.getString("jCheckXGroupTx.text")); // NOI18N
        jCheckXGroupTx.setName("jCheckXGroupTx"); // NOI18N

        jCheckXGroupMid.setText(resourceMap.getString("jCheckXGroupMid.text")); // NOI18N
        jCheckXGroupMid.setName("jCheckXGroupMid"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckXGroupTest)
                    .addComponent(jCheckXGroupMobileId)
                    .addComponent(jCheckXGroupStaticId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckXGroupTx)
                    .addComponent(jCheckXGroupMid))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckXGroupTest)
                    .addComponent(jCheckXGroupTx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckXGroupMobileId)
                    .addComponent(jCheckXGroupMid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckXGroupStaticId)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jCheckConnectWithLine.setText(resourceMap.getString("jCheckConnectWithLine.text")); // NOI18N
        jCheckConnectWithLine.setName("jCheckConnectWithLine"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckFitCurve)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextParamDirectMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextParamConstant, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jComboXValue, 0, 194, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextMaximalRefDistance, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                        .addComponent(jTextMinimalRefDistance, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                        .addComponent(jCheckConnectWithLine))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton1)
                        .addGap(150, 150, 150)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextParamConstant, jTextParamDirectMulti});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboXValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jTextParamDirectMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextParamConstant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextMinimalRefDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextMaximalRefDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckFitCurve)
                    .addComponent(jCheckConnectWithLine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // dispose
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Set current progress 
     * @param cur 
     */
    public void setProgressCur(int cur){
        
    }
    
    /**
     * set progressbar boudnaries
     * @param max 
     */
    public void setProgressMax(int max){
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // load data
        final jPannelRSSI2DistanceDataLoader dataLoader;
        if (this.parentPanel instanceof jPannelRSSI2DistanceDataLoader){
            dataLoader = (jPannelRSSI2DistanceDataLoader) this.parentPanel;

            try {
                // my parameters write here
                Map<String, Object> options = new HashMap<String, Object>();
                
                // parameter verification
                // if is empty, set default values
                if (this.jTextParamDirectMulti.getText()==null || "".equals(this.jTextParamDirectMulti.getText())){
                    this.jTextParamDirectMulti.setText("1");
                }
                
                if (this.jTextParamConstant.getText()==null || "".equals(this.jTextParamConstant.getText())){
                    this.jTextParamConstant.setText("0");
                }
                
                if (this.jTextMinimalRefDistance.getText()==null || "".equals(this.jTextMinimalRefDistance.getText())){
                    this.jTextMinimalRefDistance.setText("1");
                }
                
                if (this.jTextMaximalRefDistance.getText()==null || "".equals(this.jTextMaximalRefDistance.getText())){
                    this.jTextMaximalRefDistance.setText("1");
                }
                
                // get parameters from fields to Objects (later stored to map)
                Double directMulti = Double.valueOf(this.jTextParamDirectMulti.getText());
                Double constant = Double.valueOf(this.jTextParamConstant.getText());
                Double minimalRefDistance = Double.valueOf(this.jTextMinimalRefDistance.getText());
                Double maximalRefDistance = Double.valueOf(this.jTextMaximalRefDistance.getText());
                
                // xvalue group (define one data serie)
                Set<String> xvalueGroup = new HashSet<String>();
                // determine selected elements from group
                if (this.jCheckXGroupMid.isSelected()){
                    xvalueGroup.add("mid");
                }
                
                if (this.jCheckXGroupMobileId.isSelected()){
                    xvalueGroup.add("mobileId");
                }
                
                if (this.jCheckXGroupStaticId.isSelected()){
                    xvalueGroup.add("staticId");
                }
                
                if (this.jCheckXGroupTest.isSelected()){
                    xvalueGroup.add("testno");
                }
                
                if (this.jCheckXGroupTx.isSelected()){
                    xvalueGroup.add("txpower");
                }
                
                // if xgroup is empty, display error and exit
                if (xvalueGroup.isEmpty()){
                    JOptionPane.showMessageDialog(null,
                        "Incorrect data filled in!" + RSSI_graphApp.getLineSeparator() +
                        "Please select at least one element from X Value Group.",
                        "Data error",
                        JOptionPane.WARNING_MESSAGE);
                    
                    return;
                }
                
                options.put("XvalueGroup", xvalueGroup);
                options.put("ParamSource", this.jComboXValue.getSelectedIndex());
                options.put("ParamDirectMulti", directMulti);
                options.put("ParamConstant", constant);
                options.put("MinimalRefDistance", minimalRefDistance);
                options.put("MaximalRefDistance", maximalRefDistance);
                options.put("doCurveFit", this.jCheckFitCurve.isSelected());

                 // display info
                JOptionPane.showMessageDialog(null,
                    "Prepared for data loading." + RSSI_graphApp.getLineSeparator() +
                    "Data load will start after closing this information window, please wait until load is finished." + RSSI_graphApp.getLineSeparator() +
                    "When finished, settings dialog dissapears."    ,
                    "Information",
                    JOptionPane.INFORMATION_MESSAGE);
                
                
                // finaly, load data
                // pass options
                dataLoader.loadData(options);
            } catch (SQLException ex) {
                Logger.getLogger(jDialogLoadData.class.getName()).log(Level.SEVERE, null, ex);
                dataLoader.logToWindow("Exception thrown when loading data. E: " + ex.getMessage(), JPannelLoggerLogElement.SEVERITY_ERROR);
                dispose();
            } catch (Exception ex) {
                Logger.getLogger(jDialogLoadData.class.getName()).log(Level.SEVERE, null, ex);
                dataLoader.logToWindow("Exception thrown when loading data. E: " + ex.getMessage(), JPannelLoggerLogElement.SEVERITY_ERROR);
                dispose();
            }

            dispose();
        }
        else{
            throw new IllegalStateException("Unknown parent panel, don't know what to do");
        }

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * set default multiplicator
     */ 
    private void jComboXValueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboXValueItemStateChanged
        int selectedIndex = this.jComboXValue.getSelectedIndex();
        if (selectedIndex==0) {
            this.jTextParamDirectMulti.setText("0.01");
        } else {
            this.jTextParamDirectMulti.setText("1");
        }
    }//GEN-LAST:event_jComboXValueItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDialogLoadData dialog = new jDialogLoadData(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JPanel getParentPanel() {
        return parentPanel;
    }

    public void setParentPanel(JPanel parentPanel) {
        this.parentPanel = parentPanel;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckConnectWithLine;
    private javax.swing.JCheckBox jCheckFitCurve;
    private javax.swing.JCheckBox jCheckXGroupMid;
    private javax.swing.JCheckBox jCheckXGroupMobileId;
    private javax.swing.JCheckBox jCheckXGroupStaticId;
    private javax.swing.JCheckBox jCheckXGroupTest;
    private javax.swing.JCheckBox jCheckXGroupTx;
    private javax.swing.JComboBox jComboXValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextMaximalRefDistance;
    private javax.swing.JTextField jTextMinimalRefDistance;
    private javax.swing.JTextField jTextParamConstant;
    private javax.swing.JTextField jTextParamDirectMulti;
    // End of variables declaration//GEN-END:variables

}
