/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelLocalizationMain.java
 *
 * Created on Apr 3, 2011, 8:02:25 PM
 */

package rssi_localization.localization;

import java.awt.event.KeyEvent;

/**
 *
 * @author ph4r05
 */
public class JPanelLocalizationMain extends javax.swing.JPanel {

    /** Creates new form JPanelLocalizationMain */
    public JPanelLocalizationMain() {
        initComponents();

        // jtabbed mnemonics
    }

    public JPanelLocalizationCommand getjPanelLocalizationCommand1() {
        return jPanelLocalizationCommand1;
    }

    public JPanelLocalizationLog getjPanelLocalizationLog1() {
        return jPanelLocalizationLog1;
    }

    public JPanelLocalizationSettings getjPanelLocalizationSettings1() {
        return jPanelLocalizationSettings1;
    }

    public JPanelRSSIInTime getjPanelRSSIInTime1() {
        return jPanelRSSIInTime1;
    }

    public JPanelNetworkMap getjPanelNetworkMap1() {
        return jPanelNetworkMap1;
    }

    public void setjPanelNetworkMap1(JPanelNetworkMap jPanelNetworkMap1) {
        this.jPanelNetworkMap1 = jPanelNetworkMap1;
    }

    public JPanelDistanceInTime getjPanelDistanceInTime1() {
        return jPanelDistanceInTime1;
    }

    public void setjPanelDistanceInTime1(JPanelDistanceInTime jPanelDistanceInTime1) {
        this.jPanelDistanceInTime1 = jPanelDistanceInTime1;
    }

    public JPanelLocalizationHeuristics getjPanelLocalizationHeuristics1() {
        return jPanelLocalizationHeuristics1;
    }

    
    

    // localization HERE
    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelRSSIInTime1 = new rssi_localization.localization.JPanelRSSIInTime();
        jPanelDistanceInTime1 = new rssi_localization.localization.JPanelDistanceInTime();
        jPanelNetworkMap1 = new rssi_localization.localization.JPanelNetworkMap();
        jPanelLocalizationLog1 = new rssi_localization.localization.JPanelLocalizationLog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelLocalizationCommand1 = new rssi_localization.localization.JPanelLocalizationCommand();
        jPanelLocalizationSettings1 = new rssi_localization.localization.JPanelLocalizationSettings();
        jPanelLocalizationHeuristics1 = new rssi_localization.localization.JPanelLocalizationHeuristics();

        setName("Form"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanelRSSIInTime1.setName("jPanelRSSIInTime1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(rssi_localization.RSSI_graphApp.class).getContext().getResourceMap(JPanelLocalizationMain.class);
        jTabbedPane1.addTab(resourceMap.getString("jPanelRSSIInTime1.TabConstraints.tabTitle"), jPanelRSSIInTime1); // NOI18N

        jPanelDistanceInTime1.setName("jPanelDistanceInTime1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jPanelDistanceInTime1.TabConstraints.tabTitle"), jPanelDistanceInTime1); // NOI18N

        jPanelNetworkMap1.setName("jPanelNetworkMap1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jPanelNetworkMap1.TabConstraints.tabTitle"), jPanelNetworkMap1); // NOI18N

        jPanelLocalizationLog1.setName("jPanelLocalizationLog1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("jPanelLocalizationLog1.TabConstraints.tabTitle"), jPanelLocalizationLog1); // NOI18N

        jTabbedPane2.setName("jTabbedPane2"); // NOI18N

        jPanelLocalizationCommand1.setName("jPanelLocalizationCommand1"); // NOI18N
        jTabbedPane2.addTab(resourceMap.getString("jPanelLocalizationCommand1.TabConstraints.tabTitle"), jPanelLocalizationCommand1); // NOI18N

        jPanelLocalizationSettings1.setName("jPanelLocalizationSettings1"); // NOI18N
        jTabbedPane2.addTab(resourceMap.getString("jPanelLocalizationSettings1.TabConstraints.tabTitle"), jPanelLocalizationSettings1); // NOI18N

        jPanelLocalizationHeuristics1.setName("jPanelLocalizationHeuristics1"); // NOI18N
        jTabbedPane2.addTab(resourceMap.getString("jPanelLocalizationHeuristics1.TabConstraints.tabTitle"), jPanelLocalizationHeuristics1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );

        jTabbedPane1.setMnemonicAt(0, KeyEvent.VK_I);
        jTabbedPane1.setMnemonicAt(1, KeyEvent.VK_D);
        jTabbedPane1.setMnemonicAt(2, KeyEvent.VK_M);
        jTabbedPane1.setMnemonicAt(3, KeyEvent.VK_O);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rssi_localization.localization.JPanelDistanceInTime jPanelDistanceInTime1;
    private rssi_localization.localization.JPanelLocalizationCommand jPanelLocalizationCommand1;
    private rssi_localization.localization.JPanelLocalizationHeuristics jPanelLocalizationHeuristics1;
    private rssi_localization.localization.JPanelLocalizationLog jPanelLocalizationLog1;
    private rssi_localization.localization.JPanelLocalizationSettings jPanelLocalizationSettings1;
    private rssi_localization.localization.JPanelNetworkMap jPanelNetworkMap1;
    private rssi_localization.localization.JPanelRSSIInTime jPanelRSSIInTime1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables

}
