/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogAddToGraph.java
 *
 * Created on Apr 8, 2011, 3:44:56 PM
 */

package rssi_graph.rssi;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import rssi_graph.JPannelLoggerLogElement;
import rssi_graph.RSSI_graphApp;
import rssi_graph.utils.OptionsUtils;

/**
 *
 * @author ph4r05
 */
public class JDialogAddToGraph extends javax.swing.JDialog {

    /**
     * parent panel where show button was pressed
     */
    protected javax.swing.JPanel parentPanel = null;

    /** Creates new form JDialogAddToGraph */
    public JDialogAddToGraph(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Dimension size = new Dimension(180, 200);
        Rectangle bounds = this.getBounds();
        
        this.setMinimumSize(size);
        this.setPreferredSize(size);
        this.setBounds(bounds.x, bounds.y, 180, 200);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jComboParameter = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jCheckShowMinMax = new javax.swing.JCheckBox();
        jCheckShowQuartiles = new javax.swing.JCheckBox();
        jCheckShowOutliers = new javax.swing.JCheckBox();
        jCheckFillBox = new javax.swing.JCheckBox();
        jCheckSortXvalue = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(rssi_graph.RSSI_graphApp.class).getContext().getResourceMap(JDialogAddToGraph.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(187, 193));
        setName("Form"); // NOI18N

        jButtonAdd.setText(resourceMap.getString("jButtonAdd.text")); // NOI18N
        jButtonAdd.setName("jButtonAdd"); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jComboParameter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Distance [cm]", "Angle", "Step" }));
        jComboParameter.setName("jComboParameter"); // NOI18N
        jComboParameter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboParameterItemStateChanged(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jCheckShowMinMax.setSelected(true);
        jCheckShowMinMax.setText(resourceMap.getString("jCheckShowMinMax.text")); // NOI18N
        jCheckShowMinMax.setName("jCheckShowMinMax"); // NOI18N

        jCheckShowQuartiles.setSelected(true);
        jCheckShowQuartiles.setText(resourceMap.getString("jCheckShowQuartiles.text")); // NOI18N
        jCheckShowQuartiles.setName("jCheckShowQuartiles"); // NOI18N
        jCheckShowQuartiles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckShowQuartilesItemStateChanged(evt);
            }
        });

        jCheckShowOutliers.setText(resourceMap.getString("jCheckShowOutliers.text")); // NOI18N
        jCheckShowOutliers.setName("jCheckShowOutliers"); // NOI18N

        jCheckFillBox.setText(resourceMap.getString("jCheckFillBox.text")); // NOI18N
        jCheckFillBox.setName("jCheckFillBox"); // NOI18N

        jCheckSortXvalue.setText(resourceMap.getString("jCheckSortXvalue.text")); // NOI18N
        jCheckSortXvalue.setToolTipText(resourceMap.getString("jCheckSortXvalue.toolTipText")); // NOI18N
        jCheckSortXvalue.setName("jCheckSortXvalue"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckShowMinMax)
                    .addComponent(jCheckShowQuartiles)
                    .addComponent(jCheckFillBox)
                    .addComponent(jCheckShowOutliers)))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancel))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckSortXvalue))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAdd, jButtonCancel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckShowMinMax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckShowQuartiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckFillBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckShowOutliers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckSortXvalue)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonCancel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // close dialog/dispose
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        final jPannelRSSI2DistanceDataLoader dataLoader;
        if (this.parentPanel instanceof jPannelRSSI2DistanceDataLoader){
            // my parameters write here
            Map<String, Object> options = new HashMap<String, Object>();

            dataLoader = (jPannelRSSI2DistanceDataLoader) this.parentPanel;
            try {
                // parameter interpretation
                options.put("ParameterInterpretation", this.jComboParameter.getSelectedIndex());
                options.put("ShowQuartiles", this.jCheckShowQuartiles.isSelected());
                options.put("ShowMinMax", this.jCheckShowMinMax.isSelected());
                options.put("ShowOutliers", this.jCheckShowOutliers.isSelected());
                options.put("ChartFillBox", this.jCheckFillBox.isSelected());
                options.put("SortXvalues", this.jCheckSortXvalue.isSelected());
                
                Map<String, Object> dataOptions = dataLoader.getDataOptions();
                Set<String> xvaluegroup = null;
                if (dataOptions==null || !OptionsUtils.isOption(dataOptions, "XvalueGroup")){
                    xvaluegroup=null;
                } else {
                    xvaluegroup= (Set<String>) OptionsUtils.getOption(dataOptions, "XvalueGroup");
                }
                options.put("XvalueGroup", xvaluegroup);

                // draw graph
                dataLoader.logToWindow("Adding data to graph", JPannelLoggerLogElement.SEVERITY_DEBUG);

                // add testBuckets and then fire event data changed
                RSSI_graphApp.getApplication().getGraphViewFrame().getjPannelRSSI2DistanceChart1().setOptions(options);
                RSSI_graphApp.getApplication().getGraphViewFrame().getjPannelRSSI2DistanceChart1().addRSSIData(dataLoader.getTestBuckets());
                RSSI_graphApp.getApplication().getGraphViewFrame().getjPannelRSSI2DistanceChart1().addCurve(dataLoader.getFittedFunctions());
                RSSI_graphApp.getApplication().getGraphViewFrame().getjPannelRSSI2DistanceChart1().fireDataChanged();
                dispose();
            } catch (Exception ex) {
                Logger.getLogger(JDialogAddToGraph.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
                dataLoader.logToWindow("Exception thrown when drawing graph. E: " + ex.getMessage(), JPannelLoggerLogElement.SEVERITY_ERROR);
                dispose();
            }
        }
        else{
            throw new IllegalStateException("Unknown parent panel, don't know what to do");
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    /**
     * Disable fill box checkbox if this is disabled
     * @param evt
     */
    private void jCheckShowQuartilesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckShowQuartilesItemStateChanged
        if (evt==null) return;
        this.jCheckFillBox.setEnabled((evt.getStateChange()==evt.SELECTED));
    }//GEN-LAST:event_jCheckShowQuartilesItemStateChanged

    private void jComboParameterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboParameterItemStateChanged
        // if selected something else than first?
        if (this.jComboParameter.getSelectedIndex()==0){
            this.jCheckSortXvalue.setEnabled(false);
        } else {
            this.jCheckSortXvalue.setEnabled(true);
        }
        
    }//GEN-LAST:event_jComboParameterItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAddToGraph dialog = new JDialogAddToGraph(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JPanel getParentPanel() {
        return parentPanel;
    }

    public void setParentPanel(JPanel parentPanel) {
        this.parentPanel = parentPanel;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JCheckBox jCheckFillBox;
    private javax.swing.JCheckBox jCheckShowMinMax;
    private javax.swing.JCheckBox jCheckShowOutliers;
    private javax.swing.JCheckBox jCheckShowQuartiles;
    private javax.swing.JCheckBox jCheckSortXvalue;
    private javax.swing.JComboBox jComboParameter;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
