/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelLocalizationHeuristics.java
 *
 * Created on May 11, 2011, 11:42:32 PM
 */
package rssi_graph.localization;

import java.text.DecimalFormat;

/**
 * Settings panel for localization optimization / heuristics
 * @author ph4r05
 */
public class JPanelLocalizationHeuristics extends javax.swing.JPanel {
    WorkerLocalization worker = null;
    
    /** Creates new form JPanelLocalizationHeuristics */
    public JPanelLocalizationHeuristics() {
        initComponents();
    }
    
    /**
     * Get number of heuristic selected
     * @return 
     */
    public int getHeuristicId(){
        if (this.jRadioNoneHeuristic.isSelected()) return 0;
        else if (this.jRadio3minimal.isSelected()) return 1;
        else if (this.jRadioInverted.isSelected()) return 2;
        else if (this.jRadioUse3Constant.isSelected()) return 3;
        else return 0;
    }
    
    /**
     * Get exponent for weighted localization w_i=1/(distance^g)
     * @return 
     */
    public double getInvertedExponent(){
        String text = this.jFormattedExponent.getText();
        if (text==null || text.isEmpty()) return 0.0;
        return Double.parseDouble(text);
    }

    public WorkerLocalization getWorker() {
        return worker;
    }

    public void setWorker(WorkerLocalization worker) {
        this.worker = worker;
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioNoneHeuristic = new javax.swing.JRadioButton();
        jRadio3minimal = new javax.swing.JRadioButton();
        jRadioInverted = new javax.swing.JRadioButton();
        jFormattedExponent = new javax.swing.JFormattedTextField(DecimalFormat.getNumberInstance());
        jLabel1 = new javax.swing.JLabel();
        jRadioUse3Constant = new javax.swing.JRadioButton();

        setName("Form"); // NOI18N

        buttonGroup1.add(jRadioNoneHeuristic);
        jRadioNoneHeuristic.setSelected(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(rssi_graph.RSSI_graphApp.class).getContext().getResourceMap(JPanelLocalizationHeuristics.class);
        jRadioNoneHeuristic.setText(resourceMap.getString("jRadioNoneHeuristic.text")); // NOI18N
        jRadioNoneHeuristic.setName("jRadioNoneHeuristic"); // NOI18N

        buttonGroup1.add(jRadio3minimal);
        jRadio3minimal.setText(resourceMap.getString("jRadio3minimal.text")); // NOI18N
        jRadio3minimal.setName("jRadio3minimal"); // NOI18N

        buttonGroup1.add(jRadioInverted);
        jRadioInverted.setText(resourceMap.getString("jRadioInverted.text")); // NOI18N
        jRadioInverted.setName("jRadioInverted"); // NOI18N

        jFormattedExponent.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedExponent.setText(resourceMap.getString("jFormattedExponent.text")); // NOI18N
        jFormattedExponent.setName("jFormattedExponent"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        buttonGroup1.add(jRadioUse3Constant);
        jRadioUse3Constant.setText(resourceMap.getString("jRadioUse3Constant.text")); // NOI18N
        jRadioUse3Constant.setName("jRadioUse3Constant"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioNoneHeuristic)
                            .addComponent(jRadioInverted)
                            .addComponent(jRadio3minimal)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(jFormattedExponent, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioUse3Constant))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioNoneHeuristic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadio3minimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioInverted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioUse3Constant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedExponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jFormattedExponent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadio3minimal;
    private javax.swing.JRadioButton jRadioInverted;
    private javax.swing.JRadioButton jRadioNoneHeuristic;
    private javax.swing.JRadioButton jRadioUse3Constant;
    // End of variables declaration//GEN-END:variables
}
